@echo Building GLFW Application...
x86_64-w64-mingw32-g++ -c -I. src/main.cpp src/glad.c
@echo Compilation complete, proceeding to linking...
x86_64-w64-mingw32-g++ -o app.exe main.o glad.o -L. -lglfw3 -lopengl32 -lgdi32 -static
@echo Linking complete, running application...
.\app
